name: ChatGPT Integration
on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente pelo GitHub Actions

jobs:
  chatgpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Executar Script do ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python script.py
